version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017



  productservice:
    image: book-store-service
    container_name: book-store-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
#    depends_on:
#      - mongo_db