export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_ISUSER_LOADING = 'SET_ISUSER_LOADING';
export const SET_LOGGEDIN = 'SET_LOGGEDIN';

// Register
export const SET_REGISTER_REQUEST = 'SET_REGISTER_REQUEST';
export const SET_REGISTER = 'SET_REGISTER';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';

// Category
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CATEGORY_ERROR = 'SET_CATEGORY_ERROR';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

// TODO
export const SET_TODO = 'SET_TODO';
export const SET_TODO_ERROR = 'SET_TODO_ERROR';
export const GET_TODO = 'GET_TODO';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';


export const SET_PRODUCTS_DATA = 'SET_PRODUCTS_DATA';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const SET_BASKET_DATA = 'SET_BASKET_DATA';
export const REMOVE_BASKET_DATA = 'REMOVE_BASKET_DATA';
export const FULL_REMOVE_BASKET_DATA = 'FULL_REMOVE_BASKET_DATA';
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';

